package io.github.manishpateluk.llmagentloop;

import io.github.manishpateluk.llmrouter.config.RouterConfig;
import io.github.manishpateluk.llmrouter.model.Message;
import io.github.manishpateluk.llmagentloop.tool.UnregisteredToolHandler;
import lombok.Builder;

import java.time.Duration;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;

/**
 * A single request into {@link AgentLoop}: what to do, optionally how the agent should behave
 * and what files it has to work with, and the async callbacks it reports back through.
 *
 * <p>{@code LoopRequest.builder()} is generated by Lombok; its {@code build()} still runs through the
 * compact constructor below, so required-field validation and defaulting apply either way.
 *
 * @param prompt          required — what the caller wants done (in a chat: the user's message)
 * @param agentProfile    optional; see {@link AgentProfile}
 * @param attachments     optional files the user supplied, as bytes — images, PDFs, spreadsheets,
 *                        CSVs, documents. Images and PDFs are shown to the model directly (for models
 *                        that can take them); small text files (CSV, Markdown, JSON...) are included
 *                        as text. Every attachment is also saved to the workspace under
 *                        {@code uploads/} — when a workspace is configured and
 *                        {@link #saveAttachments()} isn't {@code false} — and the model is told where,
 *                        so tools like {@code data_query}, {@code spreadsheet_read} and
 *                        {@code document_read} can work on them. Defaults to empty.
 * @param saveAttachments optional; {@code false} keeps attachments out of the workspace (they then
 *                        only reach the model directly or as text). Defaults to {@code true}.
 * @param history         optional earlier turns of this conversation, oldest first — for callers
 *                        that keep chat history themselves. When {@code null} (the default) and the
 *                        loop has a {@code ConversationStore} and this request has a {@link #scope()},
 *                        the session's history is loaded from the store and this turn is appended to it
 *                        afterwards. When given, the store is neither read nor written for this run.
 * @param routerConfig    optional; how this run's model calls are routed — which providers/models in
 *                        what order, cost-optimized ordering, thinking level. Overrides the agent
 *                        profile's {@link AgentProfile#routerConfig()}. The loop still adds what its
 *                        own calls need (e.g. requiring tool support where tools are offered).
 * @param answerSchema    optional JSON schema for a structured version of the final answer — e.g. to
 *                        render it as cards or feed it to other code. When set, the finished answer is
 *                        converted to JSON matching the schema in one extra (metered) model call, and
 *                        the result is {@code AgentLoopResult.structuredAnswer()}; the text answer is
 *                        still produced (and streamed) as usual. The schema's top level must be an
 *                        {@code object}.
 * @param onResult        required — called once with the final {@link AgentLoopResult}
 * @param onError         required — called once if the run fails
 * @param onMessage       optional status-update callback; defaults to a no-op
 * @param answerStream    optional; receives the answer as it's written, for showing it to the user
 *                        in real time — see {@link AnswerStream}. Providers without native streaming
 *                        deliver each step's text in one piece.
 * @param maxCostUsdCents optional cost bound, in USD cents, on top of {@link AgentProfile#maxSteps()}.
 *                        {@code null} (the default) means unbounded — current no-cost-tracking
 *                        behavior. When set, cost is checked after each step completes (not mid-step,
 *                        so the bound is approximate, not exact); once accumulated cost meets or
 *                        exceeds it, the run stops and returns whatever answer it has so far,
 *                        rather than continuing to the next step.
 * @param maxDuration     optional wall-clock bound on the whole run, checked after each step;
 *                        tool calls are also cut short when they'd run past it. {@code null} (the
 *                        default) means unbounded.
 * @param onUnregisteredTool optional; resolves tool calls the model makes that aren't registered
 *                        on the {@link AgentLoop} — see {@link UnregisteredToolHandler}. Defaults to
 *                        {@link UnregisteredToolHandler#NONE}, which ends the run with an
 *                        {@link UnregisteredToolException}.
 * @param scope           optional; whose memory, workspace and conversation this run uses — see
 *                        {@link Scope}. Without one the run gets a private, throwaway scope: nothing
 *                        it saves is visible to any other run, so nothing persists between runs
 *                        either. Pass a scope (e.g. {@code Scope.forUser(userId, sessionId)}) to keep
 *                        memory, files and chat history across a user's runs.
 */
@Builder
public record LoopRequest(
        String prompt,
        AgentProfile agentProfile,
        List<InputFile> attachments,
        Boolean saveAttachments,
        List<Message> history,
        RouterConfig routerConfig,
        Map<String, Object> answerSchema,
        Consumer<AgentLoopResult> onResult,
        Consumer<Throwable> onError,
        Consumer<AgentMessage> onMessage,
        AnswerStream answerStream,
        Integer maxCostUsdCents,
        Duration maxDuration,
        UnregisteredToolHandler onUnregisteredTool,
        Scope scope) {

    /**
     * Builds a {@link LoopRequest}. Its setters are generated by Lombok; this declaration exists so
     * the type is visible to tools (like javadoc) that read source before Lombok runs.
     */
    public static class LoopRequestBuilder {
    }

    public LoopRequest {
        Objects.requireNonNull(prompt, "prompt");
        Objects.requireNonNull(onResult, "onResult");
        Objects.requireNonNull(onError, "onError");
        attachments = attachments == null ? List.of() : List.copyOf(attachments);
        saveAttachments = saveAttachments == null ? Boolean.TRUE : saveAttachments;
        history = history == null ? null : List.copyOf(history);
        if (answerSchema != null && !"object".equals(answerSchema.get("type"))) {
            throw new IllegalArgumentException("answerSchema's top level must be {\"type\": \"object\", ...}");
        }
        answerSchema = answerSchema == null ? null : Map.copyOf(answerSchema);
        onMessage = onMessage == null ? message -> { } : onMessage;
        onUnregisteredTool = onUnregisteredTool == null ? UnregisteredToolHandler.NONE : onUnregisteredTool;
        if (maxCostUsdCents != null && maxCostUsdCents <= 0) {
            throw new IllegalArgumentException("maxCostUsdCents must be positive when supplied, was " + maxCostUsdCents);
        }
        if (maxDuration != null && (maxDuration.isZero() || maxDuration.isNegative())) {
            throw new IllegalArgumentException("maxDuration must be positive when supplied, was " + maxDuration);
        }
    }
}
