package io.github.manishpateluk.llmagentloop;

import lombok.Builder;

import java.io.File;
import java.time.Duration;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;

/**
 * A single request into {@link AgentLoop}: what to do, optionally how the agent should behave
 * and what files it has to work with, and the async callbacks it reports back through.
 *
 * <p>{@link #builder()} is generated by Lombok; its {@code build()} still runs through the
 * compact constructor below, so required-field validation and defaulting apply either way.
 *
 * @param prompt          required — what the caller wants done
 * @param agentProfile    optional; see {@link AgentProfile}
 * @param files           optional file attachments; defaults to empty
 * @param onResult        required — called once with the final {@link AgentLoopResult}
 * @param onError         required — called once if the run fails
 * @param onMessage       optional status-update callback; defaults to a no-op
 * @param maxCostUsdCents optional cost bound, in USD cents, on top of {@link AgentProfile#maxSteps()}.
 *                        {@code null} (the default) means unbounded — current no-cost-tracking
 *                        behavior. When set, cost is checked after each step completes (not mid-step,
 *                        so the bound is approximate, not exact); once accumulated cost meets or
 *                        exceeds it, the run stops and returns whatever answer it has so far,
 *                        rather than continuing to the next step.
 * @param maxDuration     optional wall-clock bound on the whole run, checked the same way as
 *                        {@code maxCostUsdCents} — after each step, not mid-step. {@code null}
 *                        (the default) means unbounded.
 */
@Builder
public record LoopRequest(
        String prompt,
        AgentProfile agentProfile,
        List<File> files,
        Consumer<AgentLoopResult> onResult,
        Consumer<Throwable> onError,
        Consumer<AgentMessage> onMessage,
        Integer maxCostUsdCents,
        Duration maxDuration) {

    public LoopRequest {
        Objects.requireNonNull(prompt, "prompt");
        Objects.requireNonNull(onResult, "onResult");
        Objects.requireNonNull(onError, "onError");
        files = files == null ? List.of() : List.copyOf(files);
        onMessage = onMessage == null ? message -> { } : onMessage;
        if (maxCostUsdCents != null && maxCostUsdCents <= 0) {
            throw new IllegalArgumentException("maxCostUsdCents must be positive when supplied, was " + maxCostUsdCents);
        }
        if (maxDuration != null && (maxDuration.isZero() || maxDuration.isNegative())) {
            throw new IllegalArgumentException("maxDuration must be positive when supplied, was " + maxDuration);
        }
    }
}
